{{- if .Values.webbff.ingress.enabled -}}
{{- $fullName := include "tt-webbff.fullname" . -}}
{{- $ingressPath := .Values.inf.ingress.webbff.path -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "tt-webbff.name" . }}
    chart: {{ template "tt-webbff.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.webbff.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.webbff.ingress.ingressClassName }}
{{- if .Values.webbff.ingress.tls }}
  tls:
  {{- range .Values.webbff.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.webbff.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: webbff
                port:
                  number: 80
  {{- end }}
{{- end }}
